name: Ping Supabase Instance

on:
  schedule:
    # Run every 6 days
    - cron: '0 0 */6 * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Teams Endpoint
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl -X GET "https://xdyaxfcdlmquopsqbaxh.supabase.co/functions/v1/teams" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY"
        continue-on-error: true
